#!/usr/bin/env bash
set -e

check_file() {
  file="$1"
  if [[ ! -f "$file" ]]; then
    echo "ERROR: File not found $file"
    exit 1
  fi
}

get_comp_dir() {
  if [[ -d "/usr/share/bash-completion/completions" ]]; then
    echo "/usr/share/bash-completion/completions"
  elif [[ -d "$BASH_COMPLETION" ]]; then
    echo "$BASH_COMPLETION"
  else
    echo ''
  fi
}

# Check that 'op' is in its place
check_file "/usr/local/bin/op"

# Check that completions file is in place
compdir="$(get_comp_dir)"
if [[ -d "$compdir" ]]; then
  check_file "$compdir/op"
else
  echo "WARNING: Cannot find compdir, completions not installed"
fi

echo "Setup artifacts are OK"
