#!/usr/bin/env bash
set -e

check_file() {
  file="$1"
  if [[ ! -f "$file" ]]; then
    echo "ERROR: File not found $file"
    exit 1
  fi
}

get_comp_dir() {
  local candidates=(
    "/usr/local/share/bash-completion/completions"
    "/usr/share/bash-completion/completions"
    "/usr/local/etc/bash_completion.d"
    "/etc/bash_completion.d"
    "/opt/homebrew/share/bash-completion/completions"
    "/opt/homebrew/etc/bash_completion.d"
  )

  local dir
  for dir in "${candidates[@]}"; do
    if [[ -d "$dir" ]]; then
      echo "$dir"
      return
    fi
  done

  echo ''
}

# Check that 'op' is in its place
check_file "/usr/local/bin/op"

# Check that completions file is in place
compdir="$(get_comp_dir)"
if [[ -d "$compdir" ]]; then
  check_file "$compdir/op"
else
  echo "ERROR: Cannot find compdir, completions not installed"
  exit 1
fi

# Check man page
check_file "/usr/local/share/man/man1/op.1"

echo "Setup artifacts are OK"
