#!/usr/bin/env bash
# ---------------------------------------------------------------
# opcode - local command shortcuts
# ---------------------------------------------------------------
opcode_context() {
  usage() {
    long_usage=0

    [[ "$1" == "long" ]] && long_usage=1

    if [[ $long_usage == 1 ]]; then
      printf "opcode %s - local command shortcuts\n\n" "$VERSION"
    fi

    printf "Usage:\n"
    printf "  op CODE [ARGS]\n"
    if [[ $long_usage == 1 ]]; then
      printf "    Execute a command from the config file (%s)\n" "$CONFIG_FILE"
      printf "    Arguments will be passed to the command (use with \"\$@\")\n\n"
    fi

    printf "  op ?, -i, --info\n"
    if [[ $long_usage == 1 ]]; then
      printf "    Show all codes and their usage comments (#?)\n\n"
    fi

    printf "  op -l, --list\n"
    if [[ $long_usage == 1 ]]; then
      printf "    List command codes\n\n"
    fi

    printf "  op -s, --show\n"
    if [[ $long_usage == 1 ]]; then
      printf "    Show the config file (%s)\n\n" "$CONFIG_FILE"
    fi

    printf "  op -w, --what [CODE]\n"
    if [[ $long_usage == 1 ]]; then
      printf "    Show the command for a given code or all codes\n\n"
    fi

    printf "  op -e, --edit\n"
    if [[ $long_usage == 1 ]]; then
      printf "    Open the config file for editing\n\n"
    fi

    printf "  op -a, --add CODE COMMAND...\n"
    if [[ $long_usage == 1 ]]; then
      printf "    Append a command to the config file\n\n"
    fi

    printf "  op -h, --help\n"
    if [[ $long_usage == 1 ]]; then
      printf "    Show this message\n\n"
    fi

    printf "  op -v, --version\n"
    if [[ $long_usage == 1 ]]; then
      printf "    Show version number\n\n"
    fi
  }

  abort() {
    echo "$1" >&2
    exit "${2:-1}"
  }

  need_config() {
    if [[ ! -f $CONFIG_FILE ]]; then
      abort "Cannot find config file ($CONFIG_FILE)"
    fi
  }

  find_command() {
    need_config

    if [[ -z $CODE ]]; then
      echo "Invalid operation"
      usage
      exit 1
    fi

    COMMAND=$(get_command_from_file "exact")
    if [[ -z $COMMAND ]]; then
      COMMAND=$(get_command_from_file "fuzzy")
    fi
  }

  get_command_from_file() {
    local pattern

    if [[ $1 == "fuzzy" ]]; then
      pattern="^${CODE}[^:]*:[[:space:]]*(.*)$"
    else
      pattern="^${CODE}:[[:space:]]*(.*)$"
    fi

    local command=""
    local collect_command=false
    local temp_line=""

    while IFS= read -r line || [[ -n $line ]]; do
      if [[ -n "$temp_line" ]]; then
        trimmed_line=${line#"${line%%[![:space:]]*}"}
        temp_line="${temp_line%\\}$trimmed_line"
        if [[ "$line" =~ \\$ ]]; then
          continue
        else
          line="$temp_line"
          temp_line=""
        fi
      fi

      if [[ "$line" =~ \\$ ]]; then
        trimmed_line=${line#"${line%%[![:space:]]*}"}
        temp_line="${temp_line%\\}$trimmed_line"
        continue
      fi

      if $collect_command; then
        if [[ -z "${line}" || ! "${line}" =~ ^[[:space:]]+ ]]; then
          break
        fi

        trimmed_line="${line#"${line%%[![:space:]]*}"}"
        command="${command:+$command && }$trimmed_line"
      else
        if [[ $line =~ $pattern ]]; then
          command="${BASH_REMATCH[1]}"
          if [[ -n $command ]]; then
            break
          fi

          collect_command=true
        fi
      fi
    done <"$CONFIG_FILE"

    echo "$command"
  }

  run_command() {
    find_command
    if [[ -n $COMMAND ]]; then
      if [[ $COMMAND =~ \$ ]]; then
        eval "$COMMAND"
      else
        # shellcheck disable=SC2294
        eval "$COMMAND" "$@"
      fi
    else
      abort "Code not found: $CODE"
    fi
  }

  add_command() {
    if [[ $# -lt 2 ]]; then
      echo "Invalid operation"
      usage
      exit 1
    fi

    new_code=$1

    shift
    new_command=$(shellwords "${@}")

    echo "$new_code: $new_command" >>"$CONFIG_FILE"
    show_config
  }

  shellwords() {
    input=("$@")
    declare -a output

    for word in "${input[@]}"; do
      if [[ $word =~ [[:space:]] ]]; then
        output+=("\"$word\"")
      else
        output+=("$word")
      fi
    done

    echo "${output[@]}"
  }

  list_codes() {
    need_config
    regex="^([a-zA-Z0-9_-]+):"
    break_regex="^[[:space:]]*private[[:space:]]*$"

    # shellcheck disable=SC2162
    while IFS= read line || [ -n "$line" ]; do
      if [[ $line =~ $regex ]]; then
        printf "%s   " "${BASH_REMATCH[1]}"
      elif [[ $line =~ $break_regex ]]; then
        break
      fi
    done <"$CONFIG_FILE"
    printf "\n"
  }

  list_codes_extended() {
    need_config
    code_regex="^([a-zA-Z0-9_-]+):"
    comment_regex="^#\? ?(.*)"
    break_regex="^[[:space:]]*private[[:space:]]*$"
    header_regex="^## ?(.*)"
    comment_found=0

    echo "Usage: op COMMAND [ARGS]"

    # shellcheck disable=SC2162
    while IFS= read line || [ -n "$line" ]; do
      if [[ $line =~ $break_regex ]]; then
        break
      fi

      if [[ $line =~ $header_regex ]]; then
        printf "\n%s\n\n" "$(green "${BASH_REMATCH[1]}")"
        comment_found=0

      elif [[ $line =~ $code_regex ]]; then
        if [[ $comment_found == 1 ]]; then
          printf "\n"
          comment_found=0
        fi
        printf "  %s\n" "$(bold "${BASH_REMATCH[1]}")"

      elif [[ $line =~ $comment_regex ]]; then
        comment_found=1
        printf "    %s\n" "${BASH_REMATCH[1]}"

      fi
    done <"$CONFIG_FILE"
    printf "\n"
  }

  edit_config() {
    ${EDITOR:-vi} "$CONFIG_FILE"
  }

  show_config() {
    need_config
    cat "$CONFIG_FILE"
  }

  what_command() {
    if [[ -z "$CODE" ]]; then
      regex="^([^#:]*):[[:space:]]*(.+)$"
      break_regex="^[[:space:]]*private[[:space:]]*$"

      # shellcheck disable=SC2162
      while IFS= read line || [ -n "$line" ]; do
        if [[ $line =~ $regex ]]; then
          printf "%s: %s\n" "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"
        elif [[ $line =~ $break_regex ]]; then
          break
        fi
      done <"$CONFIG_FILE"

    else
      find_command
      if [[ -n $COMMAND ]]; then
        # shellcheck disable=SC2086
        echo $COMMAND
      else
        abort "Code not found: $CODE"
      fi

    fi
  }

  set_config_file() {
    if [[ -f "opcode" ]]; then
      CONFIG_FILE="opcode"
    else
      CONFIG_FILE="op.conf"
    fi
  }

  list_or_usage() {
    if [[ -f $CONFIG_FILE ]]; then
      list_codes
    else
      usage
    fi
  }

  send_completion() {
    [[ -z "$COMP_LINE" || ! -f $CONFIG_FILE ]] && return
    # shellcheck disable=SC2086
    set $COMP_LINE
    if [[ $# -eq 1 ]]; then
      compgen -W "$(op --list)"
    else
      compgen -W "$(op --list)" "${@: -1}"
    fi
  }

  opcode_run() {
    case "$1" in
      "") list_or_usage ;;
      \? | -i | --info) list_codes_extended ;;
      -l | --list) list_codes ;;
      -s | --show) show_config ;;
      -w | --what)
        shift
        CODE=$1
        what_command
        ;;
      -e | --edit) edit_config ;;
      -a | --add)
        shift
        add_command "$@"
        ;;
      -h | --help) usage 'long' ;;
      -v | --version) echo "$VERSION" ;;
      --completion) send_completion ;;
      *)
        CODE=$1
        shift
        run_command "$@"
        ;;
    esac
  }

  # color functions are here even if not used directly to allow using in op.conf
  green() { printf "\e[32m%b\e[0m\n" "$*"; }
  red() { printf "\e[31m%b\e[0m\n" "$*"; }
  blue() { printf "\e[34m%b\e[0m\n" "$*"; }
  bold() { printf "\e[1m%b\e[0m\n" "$*"; }

  opcode_initialize() {
    VERSION="1.0.0"
    set_config_file
    set -e
  }

  opcode_initialize
  opcode_run "$@"
}

opcode_context "$@"
