#!/usr/bin/env bash

echo "=== Saving executable to /usr/local/bin/op"
CURL_COMMAND="curl -s https://raw.githubusercontent.com/DannyBen/opcode/master/op > /usr/local/bin/op"
if [[ $EUID -ne 0 ]]; then
  sudo bash -c "$CURL_COMMAND"
  sudo chmod a+x /usr/local/bin/op
else
  bash -c "$CURL_COMMAND"
  chmod a+x /usr/local/bin/op
fi

# If op command exists
if type op > /dev/null; then
  # Which rcfile are we installing completion to?
  if [[ -f "$HOME/.bashrc" ]]; then
    rcfile="$HOME/.bashrc"
  elif [[ -f "$HOME/.zshrc" ]]; then
    rcfile="$HOME/.zshrc"
  fi

  # If we know which rc file to work with
  if [[ -n "$rcfile" ]]; then
    # If autocomplete was already installed
    if ! grep -m 1 "op --complete" "$rcfile" > /dev/null; then
      echo "=== Appending completion command to $rcfile"
      printf "\n# Opcode Completion\n" >> "$rcfile"
      printf "if command -v complete &> /dev/null ; then\n" >> "$rcfile"
      printf "  eval \$(op --complete)\n" >> "$rcfile"
      printf "fi\n\n" >> "$rcfile"
    else
      echo "=== Completion script is already present in $rcfile"
    fi

  # No ~/.bashrc or ~/.zshrc
  else
    echo "=== Completion script was not installed"
  fi

  echo "=== Done. Type 'op --help' for more info."

# op command could not be found
else
  echo "=== Setup failed."
  exit 1
fi
