#!/usr/bin/env bash

# Figure out if we need sudo or not
sudo=''
if [[ $EUID -ne 0 ]]; then
  sudo='sudo'
fi

# Download script from Github
echo "=== Saving executable to /usr/local/bin/op"
curl_command="curl -s https://raw.githubusercontent.com/DannyBen/opcode/master/op > /usr/local/bin/op"
$sudo bash -c "$curl_command"
$sudo chmod a+x /usr/local/bin/op

# Install completions
if command -v pkg-config &> /dev/null ; then
  completions_dir=$(pkg-config --variable=completionsdir bash-completion)
  if [[ -n $completions_dir ]] ; then
    echo "=== Installing autocompletions in $completions_dir"
    echo "complete -C 'op --completion' op" | $sudo tee "${completions_dir}/op" > /dev/null
  else
    echo "=== Completion script was not installed"
  fi
else
  echo "=== Completion script was not installed"
fi

# Verify
if type op > /dev/null; then
  echo "=== Done. Type 'op --help' for more info."
else
  echo "=== Setup failed."
  exit 1
fi
