#!/usr/bin/env bash

echo "=== Saving executable to /usr/local/bin/op"
CURL_COMMAND="curl -s https://raw.githubusercontent.com/DannyBen/opcode/master/op > /usr/local/bin/op"
if [[ $EUID -ne 0 ]]; then
  sudo bash -c "$CURL_COMMAND"
  sudo chmod a+x /usr/local/bin/op
else
  bash -c "$CURL_COMMAND"
  chmod a+x /usr/local/bin/op
fi

# If op command exists
if type op > /dev/null; then
  # If there is a ~/.bashrc
  if [[ -f "$HOME/.bashrc" ]]; then
    # If autocomplete was already installed
    if ! grep -m 1 "op --complete" "$HOME/.bashrc" > /dev/null; then
      echo "=== Appending completion command to ~/.bashrc"
      printf "\n# Opcode Completion\neval \$(op --complete)\n\n" >> "$HOME/.bashrc"
    else
      echo "=== Completion script is already present in ~/.bashrc"
    fi

  # No ~/.bashrc, let the user install completion manually if they want
  else
    echo "=== Completion script was not installed"
  fi

  echo "=== Done. Type 'op --help' for more info."

# op command could not be found
else
  echo "=== Setup failed."
  exit 1
fi
