#!/usr/bin/env bash
set -euo pipefail

echo Initializing installer...
tmpdir="$(mktemp -d)"
trap 'rm -rf "$tmpdir"' EXIT
cd "$tmpdir"
wget -q https://github.com/DannyBen/ssi/releases/latest/download/ssi
chmod +x ssi

./ssi log info Uninstalling opcode
./ssi uninstall bin op
./ssi uninstall man op.1
./ssi uninstall completion op
