name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Add current directory to path
      run: echo "$PWD" >> $GITHUB_PATH
    - name: Run shellcheck tests
      run: shellcheck op setup
    - name: Run approval tests
      run: test/approve

  macos:
    name: macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Add current directory to path
      run: echo "$PWD" >> $GITHUB_PATH
    - name: Upgrade the outdated bash
      run: brew install bash
    - name: Run approval tests
      run: test/approve

  ubuntu_setup:
    name: Setup on Ubuntu
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run setup
      run: ./setup
    - name: Test setup artifacts
      run: test/setup_artifacts

  macos_setup:
    name: Setup on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Upgrade the outdated bash
      run: brew install bash
    - name: Run setup
      run: ./setup
    - name: Test setup artifacts
      run: test/setup_artifacts

