name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Ubuntu

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add current directory to path
      run: echo "::add-path::$PWD"

    - name: Run shellcheck tests
      run: shellcheck op

    - name: Run approval tests
      run: test/approve

  test:
    name: Darwin

    runs-on: darwin-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add current directory to path
      run: echo "::add-path::$PWD"

    - name: Run approval tests
      run: test/approve

