name: Test on Mac
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Run test suite

    runs-on: darwin-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add current directory to path
      run: echo "::add-path::$PWD"

    - name: Run approval tests
      run: test/approve

